### ISSUE TITLE
Read/Writes limited by byte

### ISSUE THREAD

**Issue by Drewbadour** [JChristensen/extEEPROM#1]
In your readme, you claim "I/O across block, page and device boundaries is supported." However, when attempting to read from a device such as the ST Micro M24M02-02, you can't even get a full page!

It looks like everything is set up in the code properly to handle this, but using a byte to store length ruins it!

**Comment by JChristensen** [comment]
It's odd that I hadn't noticed that. This data logger project ([code](https://github.com/JChristensen/aaLogger_SW), [circuit](https://github.com/JChristensen/aaLogger_HW)) uses two [M24M02 EEPROMs](http://www.mouser.com/Search/ProductDetail.aspx?R=M24M02-DRMN6TPvirtualkey51120000virtualkey511-M24M02-DRMN6TP) and works fine, over a dozen examples having been built by me and others.

Recommend submitting a [SSCCE](http://www.sscce.org/) that demonstrates the alleged issue.

**Comment by JChristensen** [comment]
I may have misunderstood. I think you are saying that because the M24M02 has a 256 byte page size, that can't be properly represented when the argument `nBytes` is a byte type, e.g. in `byte write(unsigned long addr, byte *values, byte nBytes)`

**Comment by Drewbadour** [comment]
You are correct. Thats what I meant. Sorry for being vague.

**Comment by JChristensen** [comment]
No worries, good catch, thank you. I think all that is needed is to retype `nBytes` as uint16_t in the `read()` and `write()` functions.

**Comment by Drewbadour** [comment]
Thats exactly what I did to get it working on my end. Hasn't been tested extensively, but it works for me!

**Comment by JChristensen** [comment]
Well that's some testing, so that is worth something! Interesting that I had the variables that track bytes within `read()` and `write()` typed as uint16_t, but somehow the function arguments got overlooked. Thanks again.

**Comment by Drewbadour** [comment]
No, thank you for making an awesome library that kicks the pants off of Wire.h

**Comment by JChristensen** [comment]
Thanks for the feedback, glad you like the library!
