### ISSUE TITLE
stm32f103's Wire.h have no setClock currently

### ISSUE THREAD

**Issue by lefedor** [JChristensen/extEEPROM#10]
I've hotfixed it this way currently:

extEEPROM.cpp:

byte extEEPROM::begin(twiClockFreq_t twiFreq)
{
    Wire.begin();
    #ifndef _LIBMAPLE_STM32_H_
		Wire.setClock(twiFreq);
    #endif
    Wire.beginTransmission(_eepromAddr);
    if (_nAddrBytes == 2) Wire.write((byte)0);      //high addr byte
    Wire.write((byte)0);                            //low addr byte
    return Wire.endTransmission();
}

https://github.com/rogerclarkmelbourne/Arduino_STM32/tree/master/STM32F1/libraries/Wire

**Comment by victorpv** [comment]
You don't need that fix anymore, the stm32 wire class now has setClock.

**Comment by JChristensen** [comment]
See https://github.com/JChristensen/JC_EEPROM
