### ISSUE TITLE
.write error

### ISSUE THREAD

**Issue by joseitor** [JChristensen/extEEPROM#12]
Hello @PaoloP74,
First at all, thanks for this great library.

I think there is a problem with .write() method; if external EPPROM is not connected, Arduino gets stuck in that function. Also the same thing with .update() and .read(); they must return error command, but never get stuck.
In my case, it's used in a long time project, and I wanna be sure that if for any reason EEPROM fail, my Arduino aren't not going to be stuck in that function (or restarting using watchdog).

Best regards!

**Comment by PaoloP74** [comment]
The problem is the Arduino Wire library that is blocking.
