### ISSUE TITLE
Library verified with Microchip 24c16b

### ISSUE THREAD

**Issue by Diogko** [JChristensen/extEEPROM#17]
Hello, just checked the library with a Microchip 24C16B and it works as it should

**Comment by JChristensen** [comment]
Super, thank you!

**Comment by Diogko** [comment]
MIcrochip 24C32 is also working properly, i have lots more to test, salvaged a bunch of chips from my junk bin

**Comment by JChristensen** [comment]
Cool, thanks again!

**Comment by JChristensen** [comment]
Incorporated in https://github.com/JChristensen/JC_EEPROM
