### ISSUE TITLE
Compatibility with other processors

### ISSUE THREAD

**Issue by trlafleur** [JChristensen/extEEPROM#18]
The change below allows compatibility with other processors like the M0 by using the 
Wire.setClock() function to set the I2C bus speed. As TWBR is only available in the smaller AVR processors like the ATmega324P

(there is a pull request for this change by victorpv commented on 10 Sep 2017)

~~~
byte extEEPROM::begin(twiClockFreq_t twiFreq)
{
    Wire.begin();
    //TWBR = ( (F_CPU / twiFreq) - 16) / 2;
    Wire.setClock(twiFreq); 	// TRL 21Oct2018, compatibility with other processors
    Wire.beginTransmission(_eepromAddr);
    if (_nAddrBytes == 2) Wire.write(0);      //high addr byte
    Wire.write(0);                            //low addr byte
    return Wire.endTransmission();
}
~~~

**Comment by JChristensen** [comment]
Incorporated in https://github.com/JChristensen/JC_EEPROM
