### ISSUE TITLE
fast erase of eeprom area

### ISSUE THREAD

**Issue by mamama1** [JChristensen/extEEPROM#21]
Hi

i struggled to find a way to erase (ie zero out) eeprom contents page-wise.
i did not find another way than creating a buffer with zeros of the size of the eeprom block i wanted to erase. that'd be a huge waste of memory.

so i copied the ::write function of your lib to ::erase, removed the byte *value parameter and removed the line "values += nWrite;    //increment the input data pointer" so the same, only one page wide buffer (in my case 128 bytes) is being written over and over again to the eeprom until all the eeprom area is zeroed out (in my case around 7k!).

please consider adding a fast-erase function to your lib or please point me in the right direction, if I missed something.

thanks!

**Comment by JChristensen** [comment]
See the example sketch, there is an erase function.
