### ISSUE TITLE
Documentation for EEPROM >512k bits

### ISSUE THREAD

**Issue by ksr** [JChristensen/extEEPROM#26]
Hi, great library. For EEPROMs >512k bits the chip is connected via A2 and A1 only and A0 is a "not connect". It is important that the chip address in extEEPROM is an even number. 

ken

**Comment by JChristensen** [comment]
Hi Ken, thanks for the note, I'm not quite sure I understand. Is this a documentation issue or a code issue with the library? What chip(s), for example, do you refer to?
Best regards ... Jack
PS: I do need to update the README file; formatting issues.

**Comment by JChristensen** [comment]
Nothing heard, closing issue.
