### ISSUE TITLE
Suggestion for write function

### ISSUE THREAD

**Issue by ghost** [JChristensen/extEEPROM#27]
Hello,

Wouldn't it be better if delay was moved after the conditional break?
This way 500us would not be wasted if eeprom write is already complete at the last iteration.

```
//wait up to 50ms for the write to complete
for (uint8_t i=100; i; --i) {
    //delayMicroseconds(500);                     //no point in waiting too fast
    Wire.beginTransmission(ctrlByte);
    if (_nAddrBytes == 2) Wire.write(0);        //high addr byte
    Wire.write(0);                              //low addr byte
    txStatus = Wire.endTransmission();
    if (txStatus == 0) break;
    delayMicroseconds(500);                     //new place for delay
}
```

Best regards,
amazed

**Comment by JChristensen** [comment]
Datasheet says max write cycle time is 5ms. Do many writes complete in less than 1/10 of that time? I would advocate waiting just a little more than the average write cycle time. That may not be the same number for different devices though. My expectation is that writing to EEPROM is not a relatively fast thing. If I were really in a hurry, I might implement a non-blocking approach.

**Comment by ghost** [comment]
You're right, my suggestion wouldn't make any difference, I misled myself.
