### ISSUE TITLE
Potentional endurance problems

### ISSUE THREAD

**Issue by ghost** [JChristensen/extEEPROM#28]
Hello,

It should be noted on the library page that the write function implemented (every byte is written separately) could case endurance problems.

For example [24LC256 datasheet](https://ww1.microchip.com/downloads/aemDocuments/documents/MPD/ProductDocuments/DataSheets/24AA256-24LC256-24FC256-256-Kbit-I2C-Serial-EEPROM-20001203X.pdf) clearly states that a byte write will force the entire page to endure a write cycle!

> Note: When doing a write of less than 64 bytes,
the data in the rest of the page are
refreshed along with the data bytes being
written. This will force the entire page to
endure a write cycle, for this reason
endurance is specified per page.

Best regards,
amazed

**Comment by JChristensen** [comment]
Well aware of that; I consciously made no attempt to address it as there are costs in doing so. This is a low level library. If it makes sense for a particular application to buffer up writes, that can built on top of this library or elsewhere in the application.
