### ISSUE TITLE
Compilation error for Arduino Due

### ISSUE THREAD

**Issue by mariovaldez** [JChristensen/extEEPROM#5]
When I tried to compile for the Arduino Due:

```
extEEPROM.cpp:99:7: error: 'TWBR' was not declared in this scope
       TWBR = ( (F_CPU / twiFreq) - 16) / 2;
```

It compiles if I check if we are on an AVR:

```
    #ifdef __AVR__
      TWBR = ( (F_CPU / twiFreq) - 16) / 2;
    #endif
```

However then I think the I2C speed would default to 100kHz (I'm not sure, I'm just starting to use the Arduino Due).

**Comment by PaoloP74** [comment]
Test my fork --> https://github.com/PaoloP74/extEEPROM

**Comment by searobin** [comment]
Hi.
The released library within Arduino IDE is not compile with latest Arduino IDE.
This because the Wire.h does not include anymore the BUFFER_LENGTH macro definition.

The owner of the library should release an update.

Please let me know

Ciao
Severino

**Comment by jzalger** [comment]
> Test my fork --> https://github.com/PaoloP74/extEEPROM

Nailed it. Thanks 👍 
Also compiles fine on the Particle Photon.

**Comment by JChristensen** [comment]
https://github.com/JChristensen/JC_EEPROM now uses setClock() instead of direct register manipulation.
