### ISSUE TITLE
Library validated with Atmel AT24C256C

### ISSUE THREAD

**Issue by searobin** [JChristensen/extEEPROM#7]
HI Jack.

I validated your library with the 'Atmel AT24C256C (32k x 8)'  component.

I tested it with our 'SmartEverything' board.

It works fine without any changes, if you would like to add it in your README.md
maybe with our Software Company name it would be great.

I also added, in my fork, (  https://github.com/searobin/extEEPROM )
a further example to trigger read and write operations from console,
If you think it could be useful, I can issue a pull request.

**Comment by JChristensen** [comment]
Incorporated in https://github.com/JChristensen/JC_EEPROM
