### ISSUE TITLE
Error 9 after 256bytes and read/write not work

### ISSUE THREAD

**Issue by Arubinu** [JChristensen/extEEPROM#8]
**----------------
English Google Translate:**
Hello,

I used this library that worked perfectly and my growing little by little program.
But now I find myself with mistakes every time.

I instantiate the library in this way "**extEEPROM EEPROM( kbits_2, 1, 8 );**" for my "**ATMEL218 24C02N SU18**" (YL-90).
No error is returned by "**eeprom.begin( twiClock400kHz )**" is when reading or writing, it changes ...

In reading, I have two cases:
 - The reading goes well,
 - I have only "**9**" errors returned.
This is not random, but it depends on the program that I put on the Arduino.
I add or remove rows and sometimes it works, other times not ...

In writing, I find myself all the time with the "**9**" error when I exceed the address "**255**" or I write a sequel that continues to this address, and what has been written before is either false or nothing is written (all at **255** value) ...

```
byte    eread( unsigned long addr, byte *data, unsigned int len )
{
    byte        stat;

    stat = eeprom.read( addr, data, len );
    if ( stat )
    {
        Serial.print( "read " );
        Serial.print( addr, DEC );
        Serial.print( " -> " );
        Serial.println( stat, DEC );
    }

    return ( stat );
}

byte    ewrite( unsigned long addr, byte *data, unsigned int len )
{
    byte        stat;

    stat = eeprom.write( addr, data, len );
    if ( stat )
    {
        Serial.print( "write " );
        Serial.print( addr, DEC );
        Serial.print( " -> " );
        Serial.println( stat, DEC );
    }

    return ( stat );
}

```

I can not find a solution, thank you in advance for your help.

**----------------
French:**
Bonjour,

J'utilisais cette librairie qui fonctionnait parfaitement et mon programme grandissait petit à petit.
Mais maintenant je me retrouve avec des erreurs à chaque fois.

J'instancie la librairie de cette manière "**extEEPROM eeprom( kbits_2, 1, 8 );**" pour mon "**ATMEL218 24C02N SU18**" (YL-90).
Aucune erreur n'est retourné par "**eeprom.begin( twiClock400kHz );**", c'est lors d'une lecture ou écriture, que ça change...

En lecture, j'ai deux cas de figure:
- La lecture se passe bien,
- Je n'ai que des erreurs "**9**" retournées.
  Ce n'est pas aléatoire, mais ça dépend du programme que je met sur l'Arduino.
  J'ajoute, ou enlève des lignes et des fois ça fonctionne, d'autre fois pas...

En écriture, je me retrouve tout le temps avec l'erreur "**9**" quand je dépasse l'adresse "**255**" ou que j'écris une suite qui continue sur cette adresse, et ce qui a été écrit avant est soit faux, soit rien ne s'est écrit (tout à la valeur **255**)...

```
byte    eread( unsigned long addr, byte *data, unsigned int len )
{
    byte        stat;

    stat = eeprom.read( addr, data, len );
    if ( stat )
    {
        Serial.print( "read " );
        Serial.print( addr, DEC );
        Serial.print( " -> " );
        Serial.println( stat, DEC );
    }

    return ( stat );
}

byte    ewrite( unsigned long addr, byte *data, unsigned int len )
{
    byte        stat;

    stat = eeprom.write( addr, data, len );
    if ( stat )
    {
        Serial.print( "write " );
        Serial.print( addr, DEC );
        Serial.print( " -> " );
        Serial.println( stat, DEC );
    }

    return ( stat );
}
```

Je ne trouve pas de solution, merci d'avance pour votre aide.

**Comment by JChristensen** [comment]
Hello, I'm sorry but I cannot help debug your code. Issues submitted here need to demonstrate a clear-cut issue with the library. Suggest you try the Arduino forum, etc.
Cheers ... jc
